### ISSUE TITLE
Error message: ZBX_NOTSUPPORTED: Unsupported item key

### ISSUE THREAD

**Issue by franko108** [rafael747/zabbix-postfix#3]
Hello, 
your template looks interesting.  
Here is one typo (at least on ubuntu 18.04 and Debian 9 as well) on installation script (install_postfix_template_zabbix.sh) on line 38 must be :
`cd /etc/zabbix/zabbix_agentd.d/`  
not: cd /etc/zabbix/zabbix_agentd.conf.d/  

However, I installed it via your script and imported template, but from all existing items, only one that returns data is **Postfix queue** - the key: `pf.mailq`

I'm using zabbix-proxy and for any other requests I got answer - not existing key:  
```
$ zabbix_get -s postfix_hostname -p 10050 -k pf.delivered
ZBX_NOTSUPPORTED: Unsupported item key.
```
Same response or any keys: pf.deferred, pf.discarded, pf.rejected and so on.
Only one that responds with number of mails in the queue is: **pf.mailq**  
(ok, probably  the most important one :-)

I have zabbix-server version 4.4.7, zabbix_proxy (Zabbix) 4.4.7   
Postfix version: 3.3.0  
Python 2.7.17 (however also 3.6.9)

I can't find anything related in zabbix logs (agent or proxy).  
All the best,  
Franko

**Comment by rafael747** [comment]
Hello,
I am pretty sure that the right config dir for zabbix-agent is `/etc/zabbix/zabbix_agentd.conf.d/`

```
ubuntu@svr01:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
ubuntu@svr01:~$ 
ubuntu@svr01:~$ ls /etc/zabbix/zabbix_agentd.conf.d/
ubuntu@svr01:~$ ls /etc/zabbix/zabbix_agentd.d/
ls: cannot access '/etc/zabbix/zabbix_agentd.d/': No such file or directory
```
Regarding to the not existing keys, I think I know what is going on.
All the items in this tamplate (except for pf.malq) are active items, with mean that the client send the information to the server.
This way, for this to work, you need to make sure that the client can reach the zabbix server (or proxy) on port 10051 (by default)

`nc <zabbix-server> 10051 -vz`

Also make sure that `zabbix_sender` is installed on the client because the crontab script uses it to send the keys to the server. Try something like this:

`zabbix_sender -c /etc/zabbix/zabbix_agentd.conf -k pf.received -o 1 -vv`

Also, make sure that the **ServerActive** is correct in **/etc/zabbix/zabbix_agentd.conf**

**Comment by misterbenj34** [comment]
Hello,

I confirm what @franko108  said on
`/etc/zabbix/zabbix_agentd.d/`

On CentOs 7, Zabbix agent is not installed the same way:
```
[root@vps58 zabbix]# rpm -q centos-release
centos-release-7-7.1908.0.el7.centos.x86_64
[root@vps58 zabbix]# ls /etc/zabbix/
zabbix_agentd.conf  zabbix_agentd.d
```

**Comment by rafael747** [comment]
Hello,

You are right, **/etc/zabbix/zabbix_agentd.d/** is the correct place for CentOS. There is even a pinned issue about this: https://github.com/rafael747/zabbix-postfix/issues/2
But I couldn't remember about it at that time. 

Also, depending on which version you are using, this place can change, as noted by https://www.zabbix.com/forum/zabbix-troubleshooting-and-problems/34573-zbx_notsupported-userparameter?p=209623#post209623

This way, I am going to fix the README to include instructions for Debian and RHEL/CentOS based distros.
